### PR TITLE
Re-enable codecov.io pull request comments

### PR DESCRIPTION
**Pull request by stevedlawrence**
The default behavior for codecov.io is to create a comment for each PR
to describe how it changes codecov. We previously had this disabled, but
it makes this less visiable. Delete the codecov.io config file to
re-enable PR comments to encourage new pull requests to ensure they code
has test coverage.

DAFFODIL-2403

### CODE REVIEW

**Review by tuxji — COMMENTED** [review]
I'm not sure your change worked.  Your PR has passed all the checks but codecov hasn't added a comment to your PR even though your change was supposed to re-enable PR codecov comments.

**Comment by stevedlawrence** [comment]
Hmm, I think maybe codecov had a hiccup? The codecov for this commit says it's "Waiting for CI to complete".

https://codecov.io/github/apache/incubator-daffodil/commit/2a217d7c9041b6da9f1730c18a0fdf9314253702

I'll force push a new commit to retrigger the checks and see if works that time.

**Comment by stevedlawrence** [comment]
Still not working. According to some bugs in INFRA, we might need the Codecov app installed in this repo for comments to work. I've opened on bug to have that app added: https://issues.apache.org/jira/browse/INFRA-20922

**Review by tuxji — APPROVED** [review]
+1

Good to see it works!

**Comment by stevedlawrence** [comment]
Hmm, still not getting a comment. I'm going to try closing this PR and opening a new one to see if that fixes it.

**Pull request closed without merging**
